const INITIALIZE = 'INITIALIZE'
const SET_SORT = 'SET_SORT'
const SET_ORDER = 'SET_ORDER'
const LOADING = 'LOADING'
const UPDATE_DATA = 'UPDATE_DATA'
const ERROR_LOADING_DATA = 'ERROR_LOADING_DATA'
const TOGGLE_SORT = 'TOGGLE_SORT'
const INIT_LOCATION = 'INIT_LOCATION'
const UPDATE_LOCATION = 'UPDATE_LOCATION'
const UPDATE_Q = 'UPDATE_Q'
const INIT_Q_FIELD_VALUE = 'INIT_Q_FIELD_VALUE'
const UPDATE_Q_FIELD_VALUE = 'UPDATE_Q_FIELD_VALUE'
const UPDATE_GO_TO_PAGE_VALUE = 'UPDATE_GO_TO_PAGE_VALUE'
const UPDATE_PAGE_SIZE = 'UPDATE_PAGE_SIZE'
const UPDATE_PAGE = 'UPDATE_PAGE'
const START_DEBOUNCE_Q = 'START_DEBOUNCE_Q'
const NAVIGATE_TO_PAGE = 'NAVIGATE_TO_PAGE'
const UPDATE_TOTAL_RESULT_AND_PAGES_AND_LINKS = 'UPDATE_TOTAL_RESULT_AND_PAGES_AND_LINKS'
const UPDATE_GO_TO_PAGE_DISABLED = 'UPDATE_GO_TO_PAGE_DISABLED'
const UPDATE_SORT_CONTEXT = 'UPDATE_SORT_CONTEXT'
const RESET_SORT_CONTEXT = 'RESET_SORT_CONTEXT'
const UPDATE_HEAD_ROWS = 'UPDATE_HEAD_ROWS'
const UPDATE_BODY_ROWS = 'UPDATE_BODY_ROWS'
const TABLE_BODY_CELL_CLICKED = 'TABLE_BODY_CELL_CLICKED'
const TABLE_HEAD_INIT_CHILDREN = 'TABLE_HEAD_INIT_CHILDREN'
const UPDATE_HEAD_CELL = 'UPDATE_HEAD_CELL'

export default {
  INITIALIZE,
  SET_SORT,
  SET_ORDER,
  LOADING,
  UPDATE_DATA,
  ERROR_LOADING_DATA,
  TOGGLE_SORT,
  INIT_LOCATION,
  UPDATE_LOCATION,
  UPDATE_Q,
  INIT_Q_FIELD_VALUE,
  UPDATE_Q_FIELD_VALUE,
  UPDATE_GO_TO_PAGE_VALUE,
  UPDATE_PAGE_SIZE,
  UPDATE_PAGE,
  START_DEBOUNCE_Q,
  NAVIGATE_TO_PAGE,
  UPDATE_TOTAL_RESULT_AND_PAGES_AND_LINKS,
  UPDATE_GO_TO_PAGE_DISABLED,
  UPDATE_SORT_CONTEXT,
  RESET_SORT_CONTEXT,
  UPDATE_HEAD_ROWS,
  UPDATE_BODY_ROWS,
  TABLE_BODY_CELL_CLICKED,
  TABLE_HEAD_INIT_CHILDREN,
  UPDATE_HEAD_CELL
}