//Updata data
const GO_TO_PAGE_UPDATE_GO_TO_PAGE_FIELD_VALUE = 'GO_TO_PAGE_UPDATE_GO_TO_PAGE_FIELD_VALUE'
const GO_TO_PAGE_UPDATE_GO_TO_PAGE = 'GO_TO_PAGE_UPDATE_GO_TO_PAGE'

//Other actions
const GO_TO_PAGE_FIELD_VALUE_CHANGED_EVENT = 'GO_TO_PAGE_FIELD_VALUE_CHANGED_EVENT'
const GO_TO_PAGE_KEY_DOWN_EVENT = 'GO_TO_PAGE_KEY_DOWN_EVENT'
const GO_TO_PAGE_GO_BUTTON_CLICKED_EVENT = 'GO_TO_PAGE_GO_BUTTON_CLICKED_EVENT'

export default {
  GO_TO_PAGE_UPDATE_GO_TO_PAGE_FIELD_VALUE,
  GO_TO_PAGE_UPDATE_GO_TO_PAGE,
  GO_TO_PAGE_FIELD_VALUE_CHANGED_EVENT,
  GO_TO_PAGE_KEY_DOWN_EVENT,
  GO_TO_PAGE_GO_BUTTON_CLICKED_EVENT
}