const SORT_TOGGLE_SORT = 'SORT_TOGGLE_SORT'
const SORT_UPDATE_SORT_STATE = 'SORT_UPDATE_SORT_STATE'
const SORT_RESET_SORT_STATE = 'SORT_RESET_SORT_STATE'
const SORT_UPDATE_COMPUTED_VIEW_MODEL_CELLS = 'SORT_UPDATE_COMPUTED_VIEW_MODEL_CELLS'

export default {
  SORT_TOGGLE_SORT,
  SORT_UPDATE_SORT_STATE,
  SORT_RESET_SORT_STATE,
  SORT_UPDATE_COMPUTED_VIEW_MODEL_CELLS
}