const SET_PREVIOUS_LOCATION_QUERY = 'SET_PREVIOUS_LOCATION_QUERY'
const ROUTING_UPDATE_ROUTE = 'ROUTING_UPDATE_ROUTE'
const SET_MAKE_LINK = 'SET_MAKE_LINK'

export default {
  SET_PREVIOUS_LOCATION_QUERY,
  ROUTING_UPDATE_ROUTE,
  SET_MAKE_LINK
}