const FILTER_UPDATE_Q_FIELD_VALUE = 'FILTER_UPDATE_Q_FIELD_VALUE'
const FILTER_RESET_Q_FIELD_VALUE = 'FILTER_RESET_Q_FIELD_VALUE'

export default {
  FILTER_UPDATE_Q_FIELD_VALUE,
  FILTER_RESET_Q_FIELD_VALUE
}